version: '3'

# Creamos los servicios
services:
  mydb:                                 # Creamos el servicios mydb para identificar la imagen
    image: postgres               # Usamos la imagen postgresql en la versión 12
    volumes:
      - postgresdb:/var/lib/postgresql  # Crearemos un volumen para almacenar los datos de la db
    ports:                               
      - "5432:5432"                     # Habilitamos el puerto 5432 para acceder a la db
    environment:                        # Creamos las variables del usuario contraseña y base de datos 
      POSTGRES_USER: root              #   que se crea cuando inicia docker
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:                                # Creamos y asignamos el volumen de docker
  postgresdb:
    driver: local



  